# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestBoards', '0002_auto_20170205_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
