# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestBoards', '0003_auto_20170205_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
